spring.application.name=SeoulBike

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=bd
spring.datasource.password=1234

# MyBatis settings
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.example.seoulbike.auth.model

# Jwt token
jwt.secret=seoulBikeProjectSecretKeyForJwtTokenHS256Algorithm2025!

# i18n MessageSource
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

# Seoul Public Bike API
seoul.api.key=736467435a7072693933696864776f