spring.application.name=SeoulBike

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=bd
spring.datasource.password=1234

# MyBatis settings
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.example.seoulbike.auth.model

# Jwt token
jwt.secret=seoulBikeProjectSecretKeyForJwtTokenHS256Algorithm2025!